// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/stolostron/cluster-lifecycle-api/client/view/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ManagedClusterViews returns a ManagedClusterViewInformer.
	ManagedClusterViews() ManagedClusterViewInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ManagedClusterViews returns a ManagedClusterViewInformer.
func (v *version) ManagedClusterViews() ManagedClusterViewInformer {
	return &managedClusterViewInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
