// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	versioned "github.com/stolostron/cluster-lifecycle-api/client/view/clientset/versioned"
	internalinterfaces "github.com/stolostron/cluster-lifecycle-api/client/view/informers/externalversions/internalinterfaces"
	viewv1beta1 "github.com/stolostron/cluster-lifecycle-api/client/view/listers/view/v1beta1"
	clusterlifecycleapiviewv1beta1 "github.com/stolostron/cluster-lifecycle-api/view/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManagedClusterViewInformer provides access to a shared informer and lister for
// ManagedClusterViews.
type ManagedClusterViewInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() viewv1beta1.ManagedClusterViewLister
}

type managedClusterViewInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManagedClusterViewInformer constructs a new informer for ManagedClusterView type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManagedClusterViewInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManagedClusterViewInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManagedClusterViewInformer constructs a new informer for ManagedClusterView type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManagedClusterViewInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ViewV1beta1().ManagedClusterViews(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ViewV1beta1().ManagedClusterViews(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ViewV1beta1().ManagedClusterViews(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ViewV1beta1().ManagedClusterViews(namespace).Watch(ctx, options)
			},
		},
		&clusterlifecycleapiviewv1beta1.ManagedClusterView{},
		resyncPeriod,
		indexers,
	)
}

func (f *managedClusterViewInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManagedClusterViewInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *managedClusterViewInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterlifecycleapiviewv1beta1.ManagedClusterView{}, f.defaultInformer)
}

func (f *managedClusterViewInformer) Lister() viewv1beta1.ManagedClusterViewLister {
	return viewv1beta1.NewManagedClusterViewLister(f.Informer().GetIndexer())
}
