# Copyright Contributors to the Open Cluster Management project
version: "2"
run:
  # default concurrency is a available CPU number
  concurrency: 10
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - unconvert
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      enabled-checks:
        - appendCombine
        - boolExprSimplify
        - builtinShadow
        - docStub
        - emptyFallthrough
        - equalFold
        - hexLiteral
        - indexAlloc
        - initClause
        - methodExprCall
        - nilValReturn
        - octalLiteral
        - rangeExprCopy
        - stringXbytes
        - typeAssertChain
        - typeUnparen
        - unnecessaryBlock
        - weakCond
    lll:
      line-length: 200
      tab-width: 1
    misspell:
      locale: US
      ignore-rules:
        - cancelled
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - genfiles$
      - vendor$
      - bindata$
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - errcheck
          - maligned
          - staticcheck
        path: _test\.go$|^tests/|^samples/
      - path: (.+)\.go$
        text: composite literal uses unkeyed fields
      - linters:
          - staticcheck
        text: "SA1019:"
      - linters:
          - staticcheck
        text: "SA5011:"
      - linters:
          - staticcheck
        text: "SA4006:"
      - linters:
          - unused
        path: _test\.go$
      - linters:
          - ineffassign
        path: _test\.go$
      - linters:
          - gocritic
        path: _test\.go$
      - linters:
          - lll
        path: _test\.go$
      - linters:
          - goconst
        path: _test\.go$
      - linters:
          - misspell
        text: "contianers"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - .*_test\.go
      - genfiles$
      - vendor$
      - bindata$
      - third_party$
      - builtin$
      - examples$
