kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: flightctl-acm
  namespace: flightctl
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
          namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - "{{ .PodNamespace }}"
  policyTypes:
    - Ingress
