// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	versioned "github.com/stolostron/cluster-lifecycle-api/client/imageregistry/clientset/versioned"
	internalinterfaces "github.com/stolostron/cluster-lifecycle-api/client/imageregistry/informers/externalversions/internalinterfaces"
	imageregistryv1alpha1 "github.com/stolostron/cluster-lifecycle-api/client/imageregistry/listers/imageregistry/v1alpha1"
	clusterlifecycleapiimageregistryv1alpha1 "github.com/stolostron/cluster-lifecycle-api/imageregistry/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManagedClusterImageRegistryInformer provides access to a shared informer and lister for
// ManagedClusterImageRegistries.
type ManagedClusterImageRegistryInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() imageregistryv1alpha1.ManagedClusterImageRegistryLister
}

type managedClusterImageRegistryInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManagedClusterImageRegistryInformer constructs a new informer for ManagedClusterImageRegistry type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManagedClusterImageRegistryInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManagedClusterImageRegistryInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManagedClusterImageRegistryInformer constructs a new informer for ManagedClusterImageRegistry type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManagedClusterImageRegistryInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ImageregistryV1alpha1().ManagedClusterImageRegistries(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ImageregistryV1alpha1().ManagedClusterImageRegistries(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ImageregistryV1alpha1().ManagedClusterImageRegistries(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ImageregistryV1alpha1().ManagedClusterImageRegistries(namespace).Watch(ctx, options)
			},
		},
		&clusterlifecycleapiimageregistryv1alpha1.ManagedClusterImageRegistry{},
		resyncPeriod,
		indexers,
	)
}

func (f *managedClusterImageRegistryInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManagedClusterImageRegistryInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *managedClusterImageRegistryInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterlifecycleapiimageregistryv1alpha1.ManagedClusterImageRegistry{}, f.defaultInformer)
}

func (f *managedClusterImageRegistryInformer) Lister() imageregistryv1alpha1.ManagedClusterImageRegistryLister {
	return imageregistryv1alpha1.NewManagedClusterImageRegistryLister(f.Informer().GetIndexer())
}
