// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ManagedClusterViewListerExpansion allows custom methods to be added to
// ManagedClusterViewLister.
type ManagedClusterViewListerExpansion interface{}

// ManagedClusterViewNamespaceListerExpansion allows custom methods to be added to
// ManagedClusterViewNamespaceLister.
type ManagedClusterViewNamespaceListerExpansion interface{}
