# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .ImagePullSecretName }}"
  namespace: "{{ .KlusterletNamespace }}"
type: {{ .ImagePullSecretType }}
data:
    .dockerconfigjson: {{ .ImagePullSecretData }}
