// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ManagedClusterImageRegistryListerExpansion allows custom methods to be added to
// ManagedClusterImageRegistryLister.
type ManagedClusterImageRegistryListerExpansion interface{}

// ManagedClusterImageRegistryNamespaceListerExpansion allows custom methods to be added to
// ManagedClusterImageRegistryNamespaceLister.
type ManagedClusterImageRegistryNamespaceListerExpansion interface{}
