// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	imageregistryv1alpha1 "github.com/stolostron/cluster-lifecycle-api/imageregistry/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ManagedClusterImageRegistryLister helps list ManagedClusterImageRegistries.
// All objects returned here must be treated as read-only.
type ManagedClusterImageRegistryLister interface {
	// List lists all ManagedClusterImageRegistries in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*imageregistryv1alpha1.ManagedClusterImageRegistry, err error)
	// ManagedClusterImageRegistries returns an object that can list and get ManagedClusterImageRegistries.
	ManagedClusterImageRegistries(namespace string) ManagedClusterImageRegistryNamespaceLister
	ManagedClusterImageRegistryListerExpansion
}

// managedClusterImageRegistryLister implements the ManagedClusterImageRegistryLister interface.
type managedClusterImageRegistryLister struct {
	listers.ResourceIndexer[*imageregistryv1alpha1.ManagedClusterImageRegistry]
}

// NewManagedClusterImageRegistryLister returns a new ManagedClusterImageRegistryLister.
func NewManagedClusterImageRegistryLister(indexer cache.Indexer) ManagedClusterImageRegistryLister {
	return &managedClusterImageRegistryLister{listers.New[*imageregistryv1alpha1.ManagedClusterImageRegistry](indexer, imageregistryv1alpha1.Resource("managedclusterimageregistry"))}
}

// ManagedClusterImageRegistries returns an object that can list and get ManagedClusterImageRegistries.
func (s *managedClusterImageRegistryLister) ManagedClusterImageRegistries(namespace string) ManagedClusterImageRegistryNamespaceLister {
	return managedClusterImageRegistryNamespaceLister{listers.NewNamespaced[*imageregistryv1alpha1.ManagedClusterImageRegistry](s.ResourceIndexer, namespace)}
}

// ManagedClusterImageRegistryNamespaceLister helps list and get ManagedClusterImageRegistries.
// All objects returned here must be treated as read-only.
type ManagedClusterImageRegistryNamespaceLister interface {
	// List lists all ManagedClusterImageRegistries in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*imageregistryv1alpha1.ManagedClusterImageRegistry, err error)
	// Get retrieves the ManagedClusterImageRegistry from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*imageregistryv1alpha1.ManagedClusterImageRegistry, error)
	ManagedClusterImageRegistryNamespaceListerExpansion
}

// managedClusterImageRegistryNamespaceLister implements the ManagedClusterImageRegistryNamespaceLister
// interface.
type managedClusterImageRegistryNamespaceLister struct {
	listers.ResourceIndexer[*imageregistryv1alpha1.ManagedClusterImageRegistry]
}
