// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/stolostron/cluster-lifecycle-api/client/action/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ManagedClusterActions returns a ManagedClusterActionInformer.
	ManagedClusterActions() ManagedClusterActionInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ManagedClusterActions returns a ManagedClusterActionInformer.
func (v *version) ManagedClusterActions() ManagedClusterActionInformer {
	return &managedClusterActionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
