// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	clusterlifecycleapiactionv1beta1 "github.com/stolostron/cluster-lifecycle-api/action/v1beta1"
	versioned "github.com/stolostron/cluster-lifecycle-api/client/action/clientset/versioned"
	internalinterfaces "github.com/stolostron/cluster-lifecycle-api/client/action/informers/externalversions/internalinterfaces"
	actionv1beta1 "github.com/stolostron/cluster-lifecycle-api/client/action/listers/action/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManagedClusterActionInformer provides access to a shared informer and lister for
// ManagedClusterActions.
type ManagedClusterActionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() actionv1beta1.ManagedClusterActionLister
}

type managedClusterActionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManagedClusterActionInformer constructs a new informer for ManagedClusterAction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManagedClusterActionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManagedClusterActionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManagedClusterActionInformer constructs a new informer for ManagedClusterAction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManagedClusterActionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActionV1beta1().ManagedClusterActions(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActionV1beta1().ManagedClusterActions(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActionV1beta1().ManagedClusterActions(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActionV1beta1().ManagedClusterActions(namespace).Watch(ctx, options)
			},
		},
		&clusterlifecycleapiactionv1beta1.ManagedClusterAction{},
		resyncPeriod,
		indexers,
	)
}

func (f *managedClusterActionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManagedClusterActionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *managedClusterActionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterlifecycleapiactionv1beta1.ManagedClusterAction{}, f.defaultInformer)
}

func (f *managedClusterActionInformer) Lister() actionv1beta1.ManagedClusterActionLister {
	return actionv1beta1.NewManagedClusterActionLister(f.Informer().GetIndexer())
}
