// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/stolostron/cluster-lifecycle-api/client/imageregistry/clientset/versioned/typed/imageregistry/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeImageregistryV1alpha1 struct {
	*testing.Fake
}

func (c *FakeImageregistryV1alpha1) ManagedClusterImageRegistries(namespace string) v1alpha1.ManagedClusterImageRegistryInterface {
	return newFakeManagedClusterImageRegistries(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeImageregistryV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
