# Copyright Contributors to the Open Cluster Management project

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managedcluster-import-controller
subjects:
- kind: ServiceAccount
  name: managedcluster-import-controller
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: managedcluster-import-controller
  apiGroup: rbac.authorization.k8s.io
