# Copyright Contributors to the Open Cluster Management project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: managedcluster-import-controller
  namespace: open-cluster-management
  labels:
    app: managedcluster-import-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: managedcluster-import-controller
  template:
    metadata:
      labels:
        name: managedcluster-import-controller
    spec:
      serviceAccountName: managedcluster-import-controller
      containers:
        - name: managedcluster-import-controller
          image: managedcluster-import-controller:latest
          imagePullPolicy: IfNotPresent # This is required because in kind-clusters, the image is built locally
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "managedcluster-import-controller"
            - name: MAX_CONCURRENT_RECONCILES
              value: "10"
            - name: DEFAULT_IMAGE_REGISTRY
              value: quay.io/open-cluster-management
            - name: REGISTRATION_OPERATOR_IMAGE
              value: quay.io/open-cluster-management/registration-operator:latest
            - name: REGISTRATION_IMAGE
              value: quay.io/open-cluster-management/registration:latest
            - name: WORK_IMAGE
              value: quay.io/open-cluster-management/work:latest
            - name: GOMEMLIMIT
              value: "1750MiB"
