// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ManagedClusterActionListerExpansion allows custom methods to be added to
// ManagedClusterActionLister.
type ManagedClusterActionListerExpansion interface{}

// ManagedClusterActionNamespaceListerExpansion allows custom methods to be added to
// ManagedClusterActionNamespaceLister.
type ManagedClusterActionNamespaceListerExpansion interface{}
