// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	actionv1beta1 "github.com/stolostron/cluster-lifecycle-api/action/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ManagedClusterActionLister helps list ManagedClusterActions.
// All objects returned here must be treated as read-only.
type ManagedClusterActionLister interface {
	// List lists all ManagedClusterActions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*actionv1beta1.ManagedClusterAction, err error)
	// ManagedClusterActions returns an object that can list and get ManagedClusterActions.
	ManagedClusterActions(namespace string) ManagedClusterActionNamespaceLister
	ManagedClusterActionListerExpansion
}

// managedClusterActionLister implements the ManagedClusterActionLister interface.
type managedClusterActionLister struct {
	listers.ResourceIndexer[*actionv1beta1.ManagedClusterAction]
}

// NewManagedClusterActionLister returns a new ManagedClusterActionLister.
func NewManagedClusterActionLister(indexer cache.Indexer) ManagedClusterActionLister {
	return &managedClusterActionLister{listers.New[*actionv1beta1.ManagedClusterAction](indexer, actionv1beta1.Resource("managedclusteraction"))}
}

// ManagedClusterActions returns an object that can list and get ManagedClusterActions.
func (s *managedClusterActionLister) ManagedClusterActions(namespace string) ManagedClusterActionNamespaceLister {
	return managedClusterActionNamespaceLister{listers.NewNamespaced[*actionv1beta1.ManagedClusterAction](s.ResourceIndexer, namespace)}
}

// ManagedClusterActionNamespaceLister helps list and get ManagedClusterActions.
// All objects returned here must be treated as read-only.
type ManagedClusterActionNamespaceLister interface {
	// List lists all ManagedClusterActions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*actionv1beta1.ManagedClusterAction, err error)
	// Get retrieves the ManagedClusterAction from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*actionv1beta1.ManagedClusterAction, error)
	ManagedClusterActionNamespaceListerExpansion
}

// managedClusterActionNamespaceLister implements the ManagedClusterActionNamespaceLister
// interface.
type managedClusterActionNamespaceLister struct {
	listers.ResourceIndexer[*actionv1beta1.ManagedClusterAction]
}
