// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	versioned "github.com/stolostron/cluster-lifecycle-api/client/clusterinfo/clientset/versioned"
	internalinterfaces "github.com/stolostron/cluster-lifecycle-api/client/clusterinfo/informers/externalversions/internalinterfaces"
	clusterinfov1beta1 "github.com/stolostron/cluster-lifecycle-api/client/clusterinfo/listers/clusterinfo/v1beta1"
	clusterlifecycleapiclusterinfov1beta1 "github.com/stolostron/cluster-lifecycle-api/clusterinfo/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManagedClusterInfoInformer provides access to a shared informer and lister for
// ManagedClusterInfos.
type ManagedClusterInfoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() clusterinfov1beta1.ManagedClusterInfoLister
}

type managedClusterInfoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManagedClusterInfoInformer constructs a new informer for ManagedClusterInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManagedClusterInfoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManagedClusterInfoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManagedClusterInfoInformer constructs a new informer for ManagedClusterInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManagedClusterInfoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InternalV1beta1().ManagedClusterInfos(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InternalV1beta1().ManagedClusterInfos(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InternalV1beta1().ManagedClusterInfos(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InternalV1beta1().ManagedClusterInfos(namespace).Watch(ctx, options)
			},
		},
		&clusterlifecycleapiclusterinfov1beta1.ManagedClusterInfo{},
		resyncPeriod,
		indexers,
	)
}

func (f *managedClusterInfoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManagedClusterInfoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *managedClusterInfoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterlifecycleapiclusterinfov1beta1.ManagedClusterInfo{}, f.defaultInformer)
}

func (f *managedClusterInfoInformer) Lister() clusterinfov1beta1.ManagedClusterInfoLister {
	return clusterinfov1beta1.NewManagedClusterInfoLister(f.Informer().GetIndexer())
}
