// +build !ignore_autogenerated

// IBM Confidential
// OCO Source Materials
// (C) Copyright IBM Corporation 2020 All Rights Reserved
// The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1beta1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/open-cluster-management/rcm-controller/pkg/apis/agent/v1beta1.KlusterletConfig":       schema_pkg_apis_agent_v1beta1_KlusterletConfig(ref),
		"github.com/open-cluster-management/rcm-controller/pkg/apis/agent/v1beta1.KlusterletConfigStatus": schema_pkg_apis_agent_v1beta1_KlusterletConfigStatus(ref),
	}
}

func schema_pkg_apis_agent_v1beta1_KlusterletConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KlusterletConfig is the Schema for the klusterletconfigs API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/open-cluster-management/endpoint-operator/pkg/apis/multicloud/v1beta1.EndpointSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/open-cluster-management/rcm-controller/pkg/apis/agent/v1beta1.KlusterletConfigStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/open-cluster-management/endpoint-operator/pkg/apis/multicloud/v1beta1.EndpointSpec", "github.com/open-cluster-management/rcm-controller/pkg/apis/agent/v1beta1.KlusterletConfigStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_agent_v1beta1_KlusterletConfigStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KlusterletConfigStatus defines the observed state of KlusterletConfig",
				Type:        []string{"object"},
			},
		},
	}
}
