// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	scheme "github.com/stolostron/cluster-lifecycle-api/client/clusterinfo/clientset/versioned/scheme"
	clusterinfov1beta1 "github.com/stolostron/cluster-lifecycle-api/clusterinfo/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ManagedClusterInfosGetter has a method to return a ManagedClusterInfoInterface.
// A group's client should implement this interface.
type ManagedClusterInfosGetter interface {
	ManagedClusterInfos(namespace string) ManagedClusterInfoInterface
}

// ManagedClusterInfoInterface has methods to work with ManagedClusterInfo resources.
type ManagedClusterInfoInterface interface {
	Create(ctx context.Context, managedClusterInfo *clusterinfov1beta1.ManagedClusterInfo, opts v1.CreateOptions) (*clusterinfov1beta1.ManagedClusterInfo, error)
	Update(ctx context.Context, managedClusterInfo *clusterinfov1beta1.ManagedClusterInfo, opts v1.UpdateOptions) (*clusterinfov1beta1.ManagedClusterInfo, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, managedClusterInfo *clusterinfov1beta1.ManagedClusterInfo, opts v1.UpdateOptions) (*clusterinfov1beta1.ManagedClusterInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*clusterinfov1beta1.ManagedClusterInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*clusterinfov1beta1.ManagedClusterInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clusterinfov1beta1.ManagedClusterInfo, err error)
	ManagedClusterInfoExpansion
}

// managedClusterInfos implements ManagedClusterInfoInterface
type managedClusterInfos struct {
	*gentype.ClientWithList[*clusterinfov1beta1.ManagedClusterInfo, *clusterinfov1beta1.ManagedClusterInfoList]
}

// newManagedClusterInfos returns a ManagedClusterInfos
func newManagedClusterInfos(c *InternalV1beta1Client, namespace string) *managedClusterInfos {
	return &managedClusterInfos{
		gentype.NewClientWithList[*clusterinfov1beta1.ManagedClusterInfo, *clusterinfov1beta1.ManagedClusterInfoList](
			"managedclusterinfos",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *clusterinfov1beta1.ManagedClusterInfo { return &clusterinfov1beta1.ManagedClusterInfo{} },
			func() *clusterinfov1beta1.ManagedClusterInfoList { return &clusterinfov1beta1.ManagedClusterInfoList{} },
		),
	}
}
