// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ManagedClusterInfoListerExpansion allows custom methods to be added to
// ManagedClusterInfoLister.
type ManagedClusterInfoListerExpansion interface{}

// ManagedClusterInfoNamespaceListerExpansion allows custom methods to be added to
// ManagedClusterInfoNamespaceLister.
type ManagedClusterInfoNamespaceListerExpansion interface{}
