// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	clusterinfov1beta1 "github.com/stolostron/cluster-lifecycle-api/clusterinfo/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ManagedClusterInfoLister helps list ManagedClusterInfos.
// All objects returned here must be treated as read-only.
type ManagedClusterInfoLister interface {
	// List lists all ManagedClusterInfos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clusterinfov1beta1.ManagedClusterInfo, err error)
	// ManagedClusterInfos returns an object that can list and get ManagedClusterInfos.
	ManagedClusterInfos(namespace string) ManagedClusterInfoNamespaceLister
	ManagedClusterInfoListerExpansion
}

// managedClusterInfoLister implements the ManagedClusterInfoLister interface.
type managedClusterInfoLister struct {
	listers.ResourceIndexer[*clusterinfov1beta1.ManagedClusterInfo]
}

// NewManagedClusterInfoLister returns a new ManagedClusterInfoLister.
func NewManagedClusterInfoLister(indexer cache.Indexer) ManagedClusterInfoLister {
	return &managedClusterInfoLister{listers.New[*clusterinfov1beta1.ManagedClusterInfo](indexer, clusterinfov1beta1.Resource("managedclusterinfo"))}
}

// ManagedClusterInfos returns an object that can list and get ManagedClusterInfos.
func (s *managedClusterInfoLister) ManagedClusterInfos(namespace string) ManagedClusterInfoNamespaceLister {
	return managedClusterInfoNamespaceLister{listers.NewNamespaced[*clusterinfov1beta1.ManagedClusterInfo](s.ResourceIndexer, namespace)}
}

// ManagedClusterInfoNamespaceLister helps list and get ManagedClusterInfos.
// All objects returned here must be treated as read-only.
type ManagedClusterInfoNamespaceLister interface {
	// List lists all ManagedClusterInfos in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clusterinfov1beta1.ManagedClusterInfo, err error)
	// Get retrieves the ManagedClusterInfo from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clusterinfov1beta1.ManagedClusterInfo, error)
	ManagedClusterInfoNamespaceListerExpansion
}

// managedClusterInfoNamespaceLister implements the ManagedClusterInfoNamespaceLister
// interface.
type managedClusterInfoNamespaceLister struct {
	listers.ResourceIndexer[*clusterinfov1beta1.ManagedClusterInfo]
}
