# Copyright Contributors to the Open Cluster Management project

name: Go

on:
  push:
    branches: [ main, release-*, backplane-* ]
  pull_request:
    branches: [ main, release-*, backplane-* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
      with:
        go-version-file: go.mod

    - name: E2E Tests
      run: OCM_VERSION=${{ github.base_ref }} make e2e-test

    - if:  ${{ failure() }}
      name: Logs after Tests Failed
      run: kubectl -n open-cluster-management logs -l name=managedcluster-import-controller --tail=-1

    - if: ${{ failure() }}
      name: Setup tmate session after Tests Failed
      uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3
      timeout-minutes: 120 # 120 minutes timeout
