// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	klusterletconfigv1alpha1 "github.com/stolostron/cluster-lifecycle-api/klusterletconfig/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KlusterletConfigLister helps list KlusterletConfigs.
// All objects returned here must be treated as read-only.
type KlusterletConfigLister interface {
	// List lists all KlusterletConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*klusterletconfigv1alpha1.KlusterletConfig, err error)
	// Get retrieves the KlusterletConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*klusterletconfigv1alpha1.KlusterletConfig, error)
	KlusterletConfigListerExpansion
}

// klusterletConfigLister implements the KlusterletConfigLister interface.
type klusterletConfigLister struct {
	listers.ResourceIndexer[*klusterletconfigv1alpha1.KlusterletConfig]
}

// NewKlusterletConfigLister returns a new KlusterletConfigLister.
func NewKlusterletConfigLister(indexer cache.Indexer) KlusterletConfigLister {
	return &klusterletConfigLister{listers.New[*klusterletconfigv1alpha1.KlusterletConfig](indexer, klusterletconfigv1alpha1.Resource("klusterletconfig"))}
}
