apiVersion: v1
kind: Secret
metadata:
  name: "external-managed-kubeconfig"
  namespace: "{{ .KlusterletNamespace }}"
  {{- if .IsLocalCluster }}
  labels:
    cluster.open-cluster-management.io/backup: "import-controller"
  {{- end }}
type: Opaque
data:
  kubeconfig: {{ .ExternalManagedKubeconfig }}
